name: dokit_demo
description: dokit测试工程
version: 0.8.0
homepage: http://flutter.intra.xiaojukeji.com/index.php

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dokit:
    path: ..
  dio: 3.0.9
  path_provider: ^1.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true